version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd API
      - npm install # or pip install -r requirements.txt for Python

  build:
    commands:
      - echo Build started on `date`
      - npm run build # or any other build command

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: API
