version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd API
      - npm install # or pip install -r requirements.txt for Python

  build:
    commands:
      - echo Build started on `date`
      - cd API
      - npm start # or any other build command

artifacts:
  files:
    - "**/*"
  base-directory: API
